# hide this for now
hidden: true

# default template ("context") data
context:
  header:
    title: <Project title>
    href: "javascript:void(0)"
  menu_btn:
    text: Menu

variants:
  - name: lang-es
    context:
      header:
        title: <Título de proyecto>
      menu_btn:
        text: Menú
