# Markdown config
markdown: redcarpet
highlighter: rouge

name: Draft U.S. Web Design Standards

source: docs

version: 0.9.6

exclude:
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md
- CONTRIBUTING.md
- ".sass-cache"
- ".ruby-version"
- vendor
- node_modules

permalink: pretty

repos:
- name: Draft U.S. Web Design Standards
  description: Main repository for the Draft U.S. Web Design Standards
  url: https://github.com/18F/web-design-standards
- name: Draft U.S. Web Design Standards Assets
  description: Draft U.S. Web Design Standards visual design assets
  url: https://github.com/18F/web-design-standards-assets

google_analytics_ua: UA-48605964-43

sass:
  load_paths:
    - src/stylesheets
    - docs/_scss

#  style: :compressed

collections:
  visual:
    output: true
    permalink: /:path/
  layout-system:
    output: true
    permalink: /:path/
  elements:
    output: true
    permalink: /:path/
  components:
    output: true
    permalink: /:path/
