version: 2.1

references:
  container: &container
    docker:
      - image: circleci/node:12.13.0-browsers
        environment:
          CHROME_PATH: /usr/bin/google-chrome

  restore_deps: &restore_deps
    restore_cache:
      keys:
        - v2-uswds-dependencies-{{ checksum "package-lock.json" }}

jobs:
  build:
    <<: *container
    steps:
      - checkout
      - run:
          name: Install codeclimate
          command: sudo npm install -g codeclimate-test-reporter
      - restore_cache:
          keys:
            - v2-uswds-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v2-uswds-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Run test
          command: npm run test:ci
      - run:
          name: Run code coverage report
          command: npm run cover
      - run:
          name: Checking build
          command: |
            if [[ $(echo "$CIRCLE_BRANCH" | grep -c "pull") -le 0 ]]; then
              ls -agolf dist/
              codeclimate-test-reporter < coverage/lcov.info
            fi

  deploy:
    <<: *container
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-uswds-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install --ignore-scripts
      - run: npm rebuild node-sass
      - run:
          name: Build the USWDS package
          command: npm run release
      - run:
          name: Publish to NPM
          command: |
            npm config set "//registry.npmjs.org/:_authToken=$NPM_TOKEN"
            npm publish

workflows:
  version: 2
  circle-uswds:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
