label: Card
preview: "@uswds-content"
status: ready

variants:
  - name: compare
    label: Compare
    context:
      cards:
        - name: default
          title: Card
          content:
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Facilis earum tenetur quo cupiditate, eaque qui officia recusandae.
              Excepturi nobis dolores molestias! Quas quisquam a officia eos.
        - name: raised
          title: Card with media
          media: true
          content:
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Facilis earum tenetur quo cupiditate, eaque qui officia recusandae.
              Excepturi nobis dolores molestias! Quas quisquam a officia eos.
        - name: media
          title: Media and header first
          classes: "usa-card--header-first"
          media: true
          content:
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Facilis earum tenetur quo cupiditate, eaque qui officia recusandae.
        - name: media_inset
          title: Inset media
          classes: "usa-card--header-first"
          media: true
          media_classes: "usa-card__media--inset"
          content:
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Facilis earum tenetur quo cupiditate, eaque qui officia recusandae.
        - name: media_exdent
          title: Exdent media
          classes: "usa-card--header-first"
          media: true
          media_classes: "usa-card__media--exdent"
          content:
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Facilis earum tenetur quo cupiditate, eaque qui officia recusandae.
        - name: flag
          classes: "usa-card--flag"
          title: Flag default
          media: true
          media_classes: ""
          image_classes: ""
          flag: true
          content:
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
        - name: flag-right
          classes: "usa-card--flag usa-card--media-right"
          title: Flag media on right
          media: true
          flag: true
          content:
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.

  - name: default
    label: Default
    context:
      cards:
        - title: Default card
          media: false
          classes: "tablet:grid-col-4"
          media_classes: ""
          image_classes: ""
          content:
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Facilis earum tenetur quo cupiditate, eaque qui officia recusandae.
              Facere magnam quo nostrum amet odio ut ducimus?
        - title: The economy of cities
          media: false
          classes: "tablet:grid-col-4"
          media_classes: ""
          image_classes: ""
          content:
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Facilis earum tenetur quo cupiditate, eaque qui officia recusandae.
              Facere magnam quo nostrum amet odio ut ducimus?
        - title: Cities have the capability of providing something for everybody
          media: false
          classes: "tablet:grid-col-4"
          media_classes: ""
          image_classes: ""
          content:
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Facilis earum tenetur quo cupiditate, eaque qui officia recusandae.
              Facere magnam quo nostrum amet odio ut ducimus?

  - name: media
    label: Media
    context:
      cards:
        - title: Default media
          classes: "tablet:grid-col"
          media: true
          media_classes: ""
          image_classes: ""
          content:
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
        - title: Inset media
          classes: "usa-card--header-first tablet:grid-col"
          media: true
          media_classes: "usa-card__media--inset"
          image_classes: ""
          content:
            - Nemo illo et error deserunt qui doloremque provident
              perferendis fuga pariatur eum?
        - title: Exdent media
          classes: "tablet:grid-col"
          media: true
          media_classes: "usa-card__media--exdent"
          image_classes: ""
          content:
            - Tempore ab exercitationem distinctio iste esse
              numquam a rerum culpa at quibusdam
        - title: Media with header first
          classes: "usa-card--header-first tablet:grid-col"
          media: true
          media_classes: "usa-card__media--exdent"
          image_classes: ""
          content:
            - Tempore ab exercitationem distinctio iste esse
              numquam a rerum culpa at quibusdam

  - name: flag
    label: Flag
    context:
      cards:
        - title: Default flag
          classes: "usa-card--flag tablet:grid-col-6"
          media: true
          media_classes: ""
          image_classes: ""
          content:
            - Lorem ipsum dolor sit amet consectetur adipisicing elit.
        - title: Flag media right inset
          classes: "usa-card--flag usa-card--media-right tablet:grid-col-6"
          media: true
          media_classes: "usa-card__media--inset"
          image_classes: ""
          content:
            - Nemo illo et error deserunt qui doloremque provident
              perferendis fuga pariatur eum?
