label: Search

context:
  label: Default
  modifier: ''
  text: "Search"
  input_modifier: ''

variants:
  - name: big
    context:
      label: Big
      modifier: usa-search--big
      input_modifier: 'en-big'
  - name: small
    context:
      label: Small
      modifier: usa-search--small
      input_modifier: 'en-small'
  - name: lang-es
    context:
      label: Default (Spanish)
      text: Buscar
      modifier: ''
      input_modifier: 'es'
  - name: big-lang-es
    context:
      label: Big (Spanish)
      text: Buscar
      modifier: usa-search--big
      input_modifier: 'es-big'
  - name: small-lang-es
    context:
      label: Small (Spanish)
      text: Buscar
      modifier: usa-search--small
      input_modifier: 'es-small'

