label: Banner
status: ready

context:
  banner:
    text: "An official website of the United States government"
    action: "Here’s how you know"
  domain:
    tld: ".gov"
    heading: |
      Official websites use $TLD
    text: |
      A <strong>$TLD</strong> website belongs to an official government organization in the United States.
  https:
    heading: |
      Secure $TLD websites use HTTPS
    text: |
      A <strong>lock</strong> ($LOCK_IMG) or <strong>https://</strong> means you’ve safely connected to the $TLD website. Share sensitive information only on official, secure websites.

variants:
  - name: lang-es
    context:
      banner:
        text: "Un sitio oficial del Gobierno de Estados Unidos"
        action: "Así es como usted puede verificarlo"
      domain:
        tld: ".gov"
        heading: |
          Los sitios web oficiales usan $TLD
        text: |
          Un sitio web <strong>$TLD</strong> pertenece a una organización oficial del Gobierno de Estados Unidos.
      https:
        heading: |
          Los sitios web seguros $TLD usan HTTPS
        text: |
          Un <strong>candado</strong> ($LOCK_IMG) o <strong>https://</strong> significa que usted se conectó de forma segura a un sitio web $TLD.  Comparta información sensible sólo en sitios web oficiales y seguros.
  - name: dot-mil
    context:
      domain:
        tld: ".mil"
        text: |
          A <strong>$TLD</strong> website belongs to an official U.S. Department of Defense organization.
  - name: dot-mil-lang-es
    context:
      banner:
        text: "Un sitio oficial del Gobierno de Estados Unidos"
        action: "Así es como usted puede verificarlo"
      domain:
        tld: ".mil"
        heading: |
          Los sitios web oficiales usan $TLD
        text: |
          Un sitio web <strong>$TLD</strong> pertenece a una organización oficial del Departamento de Defensa de EE. UU.
      https:
        heading: |
          Los sitios web seguros $TLD usan HTTPS
        text: |
          Un <strong>candado</strong> ($LOCK_IMG) o <strong>https://</strong> significa que usted se conectó de forma segura a un sitio web $TLD.  Comparta información sensible sólo en sitios web oficiales y seguros.
